version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: workbee-backend
    ports:
      - "3003:3003"
    env_file:
      - ./Backend/.env.production  
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: workbee-frontend
    ports:
     - "5000:80"
    env_file:
      - ./Frontend/.env.production  
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: workbee-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
